extra["groupName"] = "kotx.minecraft.mod"
extra["modVersion"] = "1.5"
extra["modName"] = "Korgelin"
extra["kotlinVersion"] = "1.4.32"
extra["annotationsVersion"] = "17.0.0"
extra["coroutineVersion"] = "1.4.3"
extra["serializationVersion"] = "1.1.0"
