modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="customgui"
version="${file.jarVersion}"
displayName="CustomGUI Mod"
credits="TeamKun"
authors="Kotx"
description='''
It is a plugin that allows you to create your own interactive GUI in Minecraft and display it or show it to others.
'''
[[dependencies.customgui]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.customgui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
